language: go
go:
- 1.12.5
go_import_path: github.com/terraform-providers/terraform-provider-vault
script:
- make test
- make
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
env:
  global:
  - secure: JExGpcqmB+8E0u8RSqKkKoCj65yJmUU/j1cPOFoPxf9NwulvaJn1NsRSguncCdSaTBc1iKi+Qg98QJhpbz2atUjXtzS44T1O2GjuaUZgY1Z3KNAB5n0suwYDap8G4dhAo2q4jlwd1stTwNEKvuKchWyge3b0BwnAdMcIXBdh+CzJl5vepGYLrvKd7hzZ7mmre9GHMmM/DdEYBkUF6RWukRT0vZYS5G151nskOIPh4VAQZyIrqJnir1uheerYwelQT5VnE6apMKXq+6rPKDtB75TXCDmrJ+Dis6K7UMFU9PsTooPBglQVtgOIXc5wJawZNJUxHEOJvbVms1s/JcB4GR5urNXCyrsntXJCTz20uTnx+eOMxEaTkP9Y3G0CIVt3lpsvWEJjF8iqCuV01BmicN7cvibv/Ww/6eOIRlH9B6nthfN4zy/ZiS9rNO4C7HOHFGOlUopyAAuH3m2pmwI1cnyWUpePmr+3WOOU4mIYc6tBGhzFupLi3XXxyOWLEzZlaoEIDNlMBJQdj/8rnJu2C+yYgjXZ1XRXCPtPMoMndNHtW8cT+Ibpltnb/pZWsZnCjmXY0H1WfvSdKQOKrBjIRq2wIGf5dqqBZFtszLdxCPedFDO902S5QNtuObA/YGuIm3TvwqiuDJU34LJf7cLBpvBwf1gMy1RLUoSMnFWhvPE=
